toJSON consistency
abalabahaha/eris pull request #1032
Opened 2020-10-04 15:44 UTC by Khaaz

fix toJSON missing properties in some of the structures.
I might have missed some

2020-11-20 05:14 UTC, Apacheli commented
Little nitpick, but would it be worth putting the JSON properties in alphabetical order? Considering one of the last PRs made sorting changes.

2021-01-29 16:54 UTC, bsian03 requested changes

2021-01-29 16:54 UTC, bsian03 commented on lib/structures/Guild.js
> +            "approximatePresenceCount",
Keep this alphabetical

2021-01-29 16:54 UTC, bsian03 commented on lib/structures/Guild.js
> +            "approximatePresenceCount",
Also you're missing `shard`, `voiceStates`, `applicationID`, `autoRemoved`, `emojiCount`, `primaryCategoryID`, `primaryCategory`, `categories`, `keywords`, `pendingVoiceStates`, `discoverySplash`, `systemChannelFlags`, `vanityURL`

2021-01-29 16:54 UTC, bsian03 commented on lib/structures/Message.js
> +            "webhookID",
alphabetical order

2021-01-29 16:54 UTC, bsian03 commented on lib/structures/Message.js
> +            "webhookID",
Also missing `channel`, `guildID`, `referencedMessage`, `member`, `activity`, `application`

2021-03-24 23:58 UTC, bsian03 requested changes

2021-03-24 23:58 UTC, bsian03 commented on lib/structures/Guild.js
>          return super.toJSON([
`shard`, `voiceStates`, `categories`, `pendingVoiceStates`, `discoverySplash`, `vanityURL` still missing

2021-03-24 23:58 UTC, abalabahaha approved these changes

2021-03-24 23:58 UTC, merged