Document discovery_splash and features in editGuild
abalabahaha/eris pull request #1033
Opened 2020-10-04 15:46 UTC by Khaaz

discord/discord-api-docs# 1764

Not merged upstream.

2020-11-08 00:26 UTC, bsian03 commented
TS docs needed

2020-11-22 22:32 UTC, Gleb-ko commented
You should also add `discoverySplash`, `discoverySplashURL` and `dynamicDiscoverySplashURL` to Guild and `discoverySplashURL` to GuildPreview.

2020-11-22 22:49 UTC, bsian03 commented
ignore above comment, i didn't realise it was for something different

2021-01-29 17:01 UTC, bsian03 requested changes

2021-01-29 17:01 UTC, bsian03 commented on index.d.ts
> +    features: string[];
Both should be alphabetically positioned and both should also be optional
```suggestion
    discoverySplash?: string;
    features?: string[];
```

2021-01-29 17:01 UTC, bsian03 commented on index.d.ts
>      systemChannelFlags: 0 | 1 | 2;
Not sure why this isn't optional but may as well fix it here

2021-03-25 00:21 UTC, abalabahaha approved these changes

2021-03-25 00:22 UTC, merged