expose selfVideo in VoiceState
abalabahaha/eris pull request #1035
Opened 2020-10-04 15:48 UTC by Khaaz

discord/discord-api-docs# 1729
Merged upstream

2020-12-27 12:34 UTC, Gleb-ko commented
You should also implement this in `index.d.ts` as well as add selfVideo on OldVoiceState in the `voiceStateUpdatee` event

2020-12-27 12:40 UTC, bsian03 commented
Khaaz intentionally left out typings as a result of #993.. I'm sure he mentioned that a few times already
That being said he also mentioned that you can PR on his fork to add them

2021-01-29 17:43 UTC, bsian03 requested changes
Indents

2021-01-29 17:43 UTC, bsian03 commented on index.d.ts
> +	selfVideo: boolean;
```suggestion
    selfStream: boolean;
    selfVideo: boolean;
```

2021-01-29 17:43 UTC, bsian03 commented on index.d.ts
> +	selfVideo: boolean;
```suggestion
    selfStream: boolean;
    selfVideo: boolean;
```

2021-03-24 23:31 UTC, abalabahaha approved these changes

2021-03-24 23:31 UTC, merged