Redo invite to allow for non strict compilation
abalabahaha/eris pull request #1054
Opened 2020-10-25 14:12 UTC by bsian03

This one is for @DonovanDMC because I was feeling nice

2020-10-25 17:15 UTC, DonovanDMC commented on index.d.ts
> +  type InviteChannel = InvitePartialChannel | Exclude<AnyGuildChannel, CategoryChannel> | GroupChannel;
@bsian03 this

2020-10-25 17:33 UTC, DonovanDMC approved these changes, later dismissed

2020-10-25 18:14 UTC, alex-taxiera requested changes

2020-10-25 18:14 UTC, alex-taxiera commented on index.d.ts
> +  export class Invite<CT extends boolean | null, CH extends InviteChannel = InviteChannel> extends Base {
probably better idea to use a string instead of true/false/null for CT

also CT could have a default to clean up some other code

2020-10-25 19:33 UTC, alex-taxiera approved these changes, later dismissed

2020-10-25 23:00 UTC, DonovanDMC approved these changes, later dismissed

2020-11-29 13:20 UTC, abalabahaha requested changes
Unrelated changes should be in a separate PR

2020-11-29 14:35 UTC, abalabahaha approved these changes

2020-11-29 14:35 UTC, merged