Add basic support for stickers
abalabahaha/eris pull request #1062
Opened 2020-11-05 12:22 UTC by Dragory

Now updated for 0.14.0. No support for posting stickers, just sticker data in Message objects.

2020-11-08 00:00 UTC, Eight8-7020 approved these changes

2020-11-29 13:36 UTC, abalabahaha requested changes
Might as well make a class for these

2021-01-24 20:48 UTC, Khaaz commented
Navigating through PR right now, I see this haven't been updated with a class as asked so I'm upping it.
For that matter I don't personally think it's that necessary since one or 2 other structures could have been classes like Emoji and are not.

2021-03-24 21:57 UTC, abalabahaha commented
This PR and #1113 both do things slightly differently, and both seem to have small bugs. I've merged them together as 9cd3a5d

2021-03-24 21:57 UTC, closed without merging