Implemented role tags
abalabahaha/eris pull request #1109
Opened 2020-12-19 20:54 UTC by Gleb-ko

Implemented [Role tags](https://discord.com/developers/docs/topics/permissions#role-object-role-tags-structure) into the Role class as attributes `botID`, `integrationID` and `premiumSubscriber`.
- Converted the premiumSubscriber to a boolean which makes more sense than keeping it as null type

2020-12-27 13:50 UTC, bsian03 requested changes
Extra spaces you added here

2020-12-27 13:50 UTC, bsian03 commented on lib/structures/Role.js
> +            "integrationID ",
```suggestion
            "integrationID",
```

2020-12-27 13:50 UTC, bsian03 commented on lib/structures/Role.js
> +            "premiumSubscriber ",
```suggestion
            "premiumSubscriber",
```

2020-12-28 21:51 UTC, Gleb-ko commented
Thank you for pointing those out, did not notice I added them

2021-01-24 20:32 UTC, Khaaz commented on lib/structures/Role.js
> +                this.premiumSubscriber = true;
any particular reason for making this a top level field instead of being consistent with discord here?

2021-03-24 21:18 UTC, abalabahaha requested changes
Agreed, more of a fan of preserving the tags object for future proofing

2021-04-25 13:48 UTC, abalabahaha commented
Implemented in 58a658f

2021-04-25 13:48 UTC, closed without merging