Use conditional typings.
abalabahaha/eris pull request #1127
Opened 2021-01-17 00:05 UTC by oathompsonjones

Before:
```ts
const member = message.member; // This is Member | null.
const guildID = message.guildID; // This is string | undefined.
if (message instanceof TextChannel) {
    // member is still treated as Member | null.
    // guildID is still treated as string | undefined.
} else {
    // member is still treated as Member | null.
    // guildID is still treated as string | undefined.
}
```
After:
```ts
const member = message.member; // This is Member | null.
const guildID = message.guildID; // This is string | undefined.
if (message instanceof TextChannel) {
    // member is now treated as Member.
    // guildID is still treated as string.
} else {
    // member is now treated as null.
    // guildID is still treated as undefined.
}
```

On an unrelated note, `Message#addReaction(reaction: string, userID: string): Promise<void>;` and `Message#removeReaction(reaction: string, userID: string): Promise<void>;` (and all equivalent methods where usedID is one of the parameters) are both marked at deprecated for all messages. Reading the previous commits, unless I've missed something, it looks like these should only be deprecated for messages in private channels, rather than for every message.
Could someone let me know if this is the case, or if I have missed something somewhere.

2021-01-17 00:58 UTC, DonovanDMC commented
You can use `instanceof GuildChannel`, or narrowing with the `type` property.
```ts
if(message.channel instanceof Eris.GuildChannel) {}
```
![](https://butts-are.cool/2021-1-16_18-54-51.110.png)
```ts
if (message.channel.type === Eris.Constants.ChannelTypes.GUILD_TEXT || message.channel.type === Eris.Constants.ChannelTypes.GUILD_NEWS) {}
```
![](https://butts-are.cool/2021-1-16_18-55-39.625.png)

2021-01-23 18:06 UTC, oathompsonjones commented
Also now includes some Emoji typings which needed correcting to be consistent with Discord's documentation.

2021-01-30 21:49 UTC, bsian03 requested changes
L1952 should also be covered here (`webhookID`)

2021-01-30 21:49 UTC, bsian03 commented on index.d.ts
> +    available: boolean;
This is in #1096 already

2021-03-24 19:29 UTC, abalabahaha approved these changes

2021-03-24 19:29 UTC, merged