Add `interaction` prop to Messages
abalabahaha/eris pull request #1167
Opened 2021-04-04 22:52 UTC by Snazzah

Towards the end of the [Message object structure](https://discord.com/developers/docs/resources/channel#message-object-message-structure) there is an `interaction` prop for messages that are created for interactions. There is also an undocumented `member` property inside of a [MessageInteraction](https://discord.com/developers/docs/interactions/slash-commands#messageinteraction) that only shows up when the message is created in gateway.

2021-04-04 23:19 UTC, bsian03 requested changes

2021-04-04 23:19 UTC, bsian03 commented on lib/structures/Message.js
> +            this.interaction = data.interaction;
Probably better if user/member fetching was done before assigning to `this`?

2021-04-04 23:19 UTC, bsian03 commented on lib/structures/Message.js
> +* @prop {String} interaction.type The type of interaction the message was created from
```suggestion
* @prop {Number} interaction.type The type of interaction the message was created from
```

2021-04-04 23:19 UTC, bsian03 commented on index.d.ts
> +    member?: Member;
```suggestion
    member: Member | null;
```

2021-04-04 23:19 UTC, bsian03 commented on index.d.ts
> +    interaction?: MessageInteraction;
```suggestion
    interaction: MessageInteraction | null;
```

2021-04-14 18:36 UTC, abalabahaha approved these changes, later dismissed

2021-04-14 22:12 UTC, abalabahaha commented on lib/structures/Message.js
> +* @prop {Member?} interaction.member The member who invoked the interaction the message was created from
```suggestion
* @prop {Object?} interaction An object containing info about the interaction the message is responding to, if applicable
* @prop {String} interaction.id The id of the interaction
* @prop {Number} interaction.type The type of interaction
* @prop {User} interaction.user The user who invoked the interaction
* @prop {Member?} interaction.member The member who invoked the interaction
```

2021-04-14 22:13 UTC, abalabahaha approved these changes

2021-04-14 22:13 UTC, merged