Enhancements for VoiceChannel join methods
abalabahaha/eris pull request #1195
Opened 2021-05-03 21:44 UTC by 5antos

Added options to choose if the bot connects to a voice channel being muted or deafened instead of always joining without being muted and deafened.

2021-05-04 23:11 UTC, almeidx requested changes

2021-05-04 23:11 UTC, almeidx commented on index.d.ts
> +    joinVoiceChannel(channelID: string, options?: { opusOnly?: boolean; shared?: boolean, selfMute?: boolean, selfDeaf?: boolean }): Promise<VoiceConnection>;
```suggestion
    joinVoiceChannel(channelID: string, options?: { opusOnly?: boolean; shared?: boolean; selfMute?: boolean; selfDeaf?: boolean }): Promise<VoiceConnection>;
```

2021-05-04 23:11 UTC, almeidx commented on index.d.ts
> +    join(options: { opusOnly?: boolean; shared?: boolean, selfMute?: boolean, selfDeaf?: boolean }): Promise<VoiceConnection>;
```suggestion
    join(options: { opusOnly?: boolean; shared?: boolean; selfMute?: boolean; selfDeaf?: boolean }): Promise<VoiceConnection>;
```

2021-07-02 22:22 UTC, bsian03 requested changes

2021-07-02 22:22 UTC, bsian03 commented on index.d.ts
> +    joinVoiceChannel(channelID: string, options?: { opusOnly?: boolean; shared?: boolean; selfMute?: boolean; selfDeaf?: boolean }): Promise<VoiceConnection>;
Can this and the same one at L2596 be in its own interface?

2021-08-03 17:01 UTC, bsian03 commented
Any update on this?

2021-08-06 21:36 UTC, Catboi8 commented
If there are no replies within a day or so I'll assume this is abandoned and pick it up myself

2021-08-29 22:16 UTC, bsian03 submitted a review, later dismissed

2021-08-29 22:16 UTC, bsian03 commented
Flipping conflict

2021-08-29 22:18 UTC, bsian03 approved these changes

2021-08-29 22:18 UTC, merged