Use "const" over "var"
abalabahaha/eris pull request #1229
Opened 2021-06-26 03:25 UTC by J-Human

This prefers the use of constants over the "var" keyword for the bot sample located in the ReadMe.

2021-07-13 14:11 UTC, NotMarx requested changes

2021-07-13 14:11 UTC, NotMarx commented on README.md
> +const bot = new Eris("Bot TOKEN");
Due to PR #1038 was merged, intents are now required for bots to operate.

2021-08-12 07:51 UTC, averageftw commented
You specified the intents, and that seems fine, but changing `var bot` to `const bot` does not actually matter much as nobody will be stupid enough to actually reassign the `bot` into something else.

2021-08-12 09:53 UTC, bsian03 commented
Which is also the reason why the PR hasn't been merged and why it has the farming label applied to it. Kinda obvious

2021-08-12 10:11 UTC, J-Human commented
I don't have any bad intention regarding this repository but showing this kind of tolerance seems a bit too much, honestly speaking. It's quite simple:
* What's the exclusive "farming" tag for? It simply shows you can't handle situations well and instead shaming the author. Maybe renaming it into "invalid" would do.
* If this PR is too low for your standards, why don't you close it? 

What's the purpose for not minding this as if it's bullshit? I get avergateftw's point but I feel having a good code convention in your sample will help. It just shows that you have good habits.

2021-08-12 10:13 UTC, bsian03 commented
The PR is valid, it's just low effort. Those kinds of PRs should have the farming label applied. I'm not discriminating your PRs, I've had to apply the same label on my own PRs updating the readme

2021-08-12 10:14 UTC, bsian03 commented
My wording earlier might not've been the best (I did literally just wake up) so if it came across the wrong way, apologies

2021-08-19 11:35 UTC, abalabahaha commented on README.md
> +    ];
Syntax error

2021-11-12 00:49 UTC, abalabahaha approved these changes

2021-11-12 00:50 UTC, merged