Prevent "User associated with Member not found"
abalabahaha/eris pull request #1260
Opened 2021-08-13 07:10 UTC by retraigo

When `client.users.limit` is set to `0`, new messages throw `Error: User associated with Member not found` due to the user not being cached. Virtually, it should also happen when the cache limit is set to a really low value and the client receives a lot of messages at once. 

As a fix, send "user" along with "member" when creating a Message. This should make the client use `data.user` in the absence of a cached user.

2021-08-13 10:58 UTC, Catboi8 commented
isn't the user already sent via message.author?

2021-08-13 11:10 UTC, bit0r1n requested changes

2021-08-13 16:02 UTC, retraigo commented
> isn't the user already sent via message.author?

I meant the error thrown from the Member class when the user associated with the member is not found in cache. To reproduce this, just create an eris client with `client.users.limit` set to `0` and send a message in a channel the bot has access to.

2021-08-19 12:57 UTC, abalabahaha approved these changes

2021-08-19 12:59 UTC, merged