Role icon support
abalabahaha/eris pull request #1278
Opened 2021-09-30 00:43 UTC by iiFDCT

2021-09-30 00:47 UTC, DonovanDMC requested changes

2021-09-30 00:47 UTC, DonovanDMC commented on lib/gateway/Shard.js
> +                * @prop {String?} icon The hash of the role's icon image, or null if no icon
```suggestion
                * @prop {String?} oldRole.icon The hash of the role's icon image, or null if no icon
```

2021-09-30 00:47 UTC, DonovanDMC commented on lib/gateway/Shard.js
> +                * @prop {String?} unicodeEmoji Unicode emoji for the role
```suggestion
                * @prop {String?} oldRole.unicodeEmoji Unicode emoji for the role
```

2021-09-30 10:56 UTC, bsian03 commented
it's not october yet

2021-10-01 11:41 UTC, DonovanDMC requested changes

2021-10-01 11:41 UTC, DonovanDMC commented on index.d.ts
> +  type GuildFeatures = "ANIMATED_ICON" | "BANNER" | "COMMERCE" | "COMMUNITY" | "DISCOVERABLE" | "FEATURABLE" | "INVITE_SPLASH" | "MEMBER_VERIFICATION_GATE_ENABLED" | "NEWS" | "PARTNERED" | "PREVIEW_E
```suggestion
  type GuildFeatures = "ANIMATED_ICON" | "BANNER" | "COMMERCE" | "COMMUNITY" | "DISCOVERABLE" | "FEATURABLE" | "INVITE_SPLASH" | "MEMBER_VERIFICATION_GATE_ENABLED" | "NEWS" | "PARTNERED" | "PREVIEW_ENABLED" | "ROLE_ICONS" | "VANITY_URL" | "VERIFIED" | "VIP_REGIONS" | "WELCOME_SCREEN_ENABLED" | "TICKETED_EVENTS_ENABLED" | "MONETIZATION_ENABLED" | "MORE_STICKERS" | "THREE_DAY_THREAD_ARCHIVE" | "SEVEN_DAY_THREAD_ARCHIVE" | "PRIVATE_THREADS";
```

Spacing
(and honestly, we should split this up between lines at some point, this is a mess {maybe by similar being grouped?})

2021-10-08 14:36 UTC, bsian03 requested changes

2021-10-08 14:36 UTC, bsian03 commented on lib/Client.js
>      * @arg {BigInt | Number | String | Permission} [options.permissions] The role permissions
Needs snake_case handling

2021-10-08 14:36 UTC, bsian03 commented on lib/gateway/Shard.js
> +                * @prop {String?} oldRole.icon The hash of the role's icon image, or null if no icon
"role's icon image" sounds weird imo

2021-10-23 16:42 UTC, bsian03 approved these changes

2021-10-23 16:42 UTC, merged