Adding missing message activity flags
abalabahaha/eris pull request #1288
Opened 2021-10-23 01:43 UTC by Awoocado

discord/discord-api-docs#3877

2021-10-23 11:34 UTC, bsian03 requested changes
They aren't bitshifted as according to docs

2021-10-23 11:48 UTC, Awoocado commented
wait, do MessageActivityTypes in Constants need `<<` ?

2021-10-23 12:06 UTC, bsian03 requested changes
Yes. They aren't types, they're flags (please don't rename for now, I'll have a look later at the implications of changing them)

2021-10-23 12:06 UTC, bsian03 commented on index.d.ts
> +      INSTANCE: 0;
```suggestion
      INSTANCE: 1;
```

2021-10-30 23:26 UTC, bsian03 commented
Feel free to change the names and I'll merge this in soon as

2021-10-30 23:59 UTC, bsian03 approved these changes

2021-10-31 00:00 UTC, merged