fix rawWS data.resolved being overwrited by CommandInteraction
abalabahaha/eris pull request #1295
Opened 2021-11-11 19:07 UTC by Dramex

While i hate this but it's the only way to fix data.resolved being overwrited in rawWS. 
this is the style of code that has been followed in all other events.

2021-11-11 19:20 UTC, Catboi8 commented
You are missing some of info.data.options, https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-interaction-data-option-structure

2021-11-11 19:22 UTC, DonovanDMC commented
considering how often interactions are changing, we shouldn't be manually doing options like that

2021-11-11 19:24 UTC, DonovanDMC commented
if you want to avoid references, cloning the object would be 1000x easier
something like 
```
Object.assign(Object.create(null), object)
```
is easy to do, though I don't know the performance impacts

2021-11-11 19:24 UTC, Dramex commented
> considering how often interactions are changing, we shouldn't be manually doing options like that

what do you suggest to fix the overwrite

2021-11-11 19:28 UTC, Catboi8 commented
> > considering how often interactions are changing, we shouldn't be manually doing options like that
> 
> what do you suggest to fix the overwrite

in case you missed it
https://github.com/abalabahaha/eris/pull/1295#issuecomment-966563904

2021-11-11 19:30 UTC, Dramex commented
> if you want to avoid references, cloning the object would be 1000x easier something like
> 
> ```
> Object.assign(Object.create(null), object)
> ```
> 
> is easy to do, though I don't know the performance impacts (and deep links can still exist)
i just followed other events. 
i'll leave this decision to @Catboi8, tell me what you think and I'll do another PR for what you purpose to clean the commits by this PR.

2021-11-11 19:32 UTC, DonovanDMC commented
Something along the lines of object spreading and null prototypes could easily solve it, but once again, someone else needs to weigh in on the performance impacts (this is messy, but works, and doesn't hardcode anything but resolved)
```
this.data = Object.assign(
	Object.create(null), info.data, {
		resolved: Object.assign(Object.create(null), info.data.resolved)
	}
);
```

![](https://butts-are.cool/chrome_11-11-2021_13-32-13.png)

2021-11-11 19:33 UTC, DonovanDMC commented
hardcoding properties is fine for other events because they don't change often
interactions are actively changing

2021-11-11 19:34 UTC, Catboi8 commented
Personally that's what I would do atm atleast until interactions is more stable, tho yea I agree the performance impacts should probably be tested

2021-11-11 20:03 UTC, Dramex commented
A better solution is to keep this as a known issue until interaction become more stable 😝

2021-11-11 20:04 UTC, DonovanDMC commented
that will likely be 5 months down the line

2021-11-11 20:07 UTC, Catboi8 commented
If you really want to do this then probably just mark the pr as a draft and wait

2021-11-11 22:49 UTC, bsian03 requested changes
Can just JSON clone info.data

2021-11-13 13:53 UTC, Catboi8 approved these changes

2021-11-14 12:17 UTC, bsian03 approved these changes
There is a more efficient way of cloning as mentioned in the server but we'll use this for now

2021-11-14 12:18 UTC, merged