chore(typings): Add missing types and reorganise
abalabahaha/eris pull request #1303
Opened 2021-11-16 23:03 UTC by bsian03

2021-11-16 23:08 UTC, Catboi8 commented
Imagine not linting

2021-11-17 03:14 UTC, abalabahaha requested changes
Reverts #1299 and #1300

2022-04-11 19:41 UTC, curtisf approved these changes
ts is hard

2022-04-12 00:46 UTC, abalabahaha approved these changes

2022-04-12 00:47 UTC, merged