Rewrite Some Interaction Types
abalabahaha/eris pull request #1309
Opened 2021-11-28 21:23 UTC by DonovanDMC

Currently interactions can be hard to use due to the way the types have been made. This pull request completely rewrites most of the `ApplicationCommandOptions*` types, and adds several unions to make accessing values neater.

### Overall Changes:
+ `ApplicationCommandOptionTypes*` - Choices, Autocomplete, MinMax
+ `ApplicationCommandOptionsWith*` - Choices, Autocomplete, MinMax
^ these are dynamic, based on `ApplicationCommandOptionTypes*`
+ new interfaces for generic options, autocomplete, choices, and min/max
+ `ApplicationCommandOptions*` have been vastly simplified
+ `InteractionOptions` has been converted into `InteractionResponse`, and the data property has been strictly typed
+ the `options` of `InteractionDataOptionsSubCommand` and `InteractionDataOptionsSubCommandGroup` has been narrowed to the valid options
- removed `PingInteraction` from the `interactionCreate` event, these are rest only
- removed `UnknownInteraction` - this makes the types very hard to use, and nothing else has an unknown variant, so this is an outlier

2021-11-29 01:08 UTC, eritbh requested changes
Missed one plural type name, also found a bug from the original implementation that should be corrected

2021-11-29 01:08 UTC, eritbh commented on index.d.ts
> +  type InteractionDataOptionsWithValue = InteractionDataOptionString | InteractionDataOptionInteger | InteractionDataOptionBoolean | InteractionDataOptionUser | InteractionDataOptionChannel | Interac
```suggestion
  type InteractionDataOptionWithValue = InteractionDataOptionString | InteractionDataOptionInteger | InteractionDataOptionBoolean | InteractionDataOptionUser | InteractionDataOptionChannel | InteractionDataOptionRole | InteractionDataOptionMentionable | InteractionDataOptionNumber;
```

2021-11-29 01:08 UTC, eritbh commented on index.d.ts
> +  type InteractionDataOption = InteractionDataOptionSubCommand | InteractionDataOptionSubCommandGroup | InteractionDataOptionsWithValue;
```suggestion
  type InteractionDataOption = InteractionDataOptionSubCommand | InteractionDataOptionSubCommandGroup | InteractionDataOptionWithValue;
```

2021-11-29 01:08 UTC, eritbh commented on index.d.ts
> +    options?: InteractionDataOptionsWithValue[];
```suggestion
    options?: InteractionDataOptionWithValue[];
```

2021-11-29 01:08 UTC, eritbh commented on index.d.ts
> +  type InteractionType = Constants["ApplicationCommandTypes"][keyof Constants["ApplicationCommandTypes"]];
`ApplicationCommandType` is assigned the same exact type later in the file, assuming this should be from `Constants.InteractionTypes` instead

```suggestion
  type InteractionType = Constants["InteractionTypes"][keyof Constants["InteractionTypes"]];
```

2021-11-29 13:19 UTC, eritbh approved these changes, later dismissed

2022-02-10 09:24 UTC, bsian03 commented
This conflicts with #1303, my plan was to merge that first

2022-02-10 09:30 UTC, DonovanDMC commented
Converted to draft until #1303 is merged

2022-03-06 16:15 UTC, coolcalcacol commented on index.d.ts
>      description: T extends Constants["ApplicationCommandTypes"]["CHAT_INPUT"] ? string : never;
Perhaps remove this field and alter the ChatInputApplicationCommand to be this: 
```js
type ChatInputApplicationCommand = ApplicationCommand<Constants['ApplicationCommandTypes']['CHAT_INPUT']> & { description: string };
```
```suggestion
    
```

2022-04-12 14:16 UTC, bsian03 commented
This should resolve all the conflicts, but I have not thoroughly checked for duplicates or unused types and interfaces as it seems like some of them aren't referenced when they should

This can also still be cleaned up

2022-04-13 02:01 UTC, bsian03 commented on index.d.ts
> +  interface ApplicationCommandBase<T extends ApplicationCommandTypes = ApplicationCommandTypes> {
Pluralise here (and relevant locations) too please

2022-04-13 22:54 UTC, bsian03 requested changes
Currently discussing in Discord

2022-04-19 17:01 UTC, bsian03 requested changes

2022-04-19 17:01 UTC, bsian03 commented on index.d.ts
> +      };
These should be in its own interface

2022-04-19 19:21 UTC, bsian03 requested changes

2022-04-19 19:21 UTC, bsian03 commented on index.d.ts
>    }
All of these should be in the relevant interfaces section, not between classes

2022-04-19 19:21 UTC, bsian03 commented on index.d.ts
>    export class AutocompleteInteraction<T extends PossiblyUncachedTextable = TextableChannel> extends Interaction {
```suggestion
  }
  
  export class AutocompleteInteraction<T extends PossiblyUncachedTextable = TextableChannel> extends Interaction {
```

2022-04-19 19:21 UTC, bsian03 commented on index.d.ts
> +
See earlier about interface position

2022-05-23 14:01 UTC, bsian03 submitted a review, later dismissed

2022-05-23 14:01 UTC, bsian03 commented on lib/Client.js
> +        }
We don't do handling for missing guild ID in other locations (see getGuildDiscovery below for reference). Please also remove this in the methods above (and anywhere else where this is present)

2022-05-23 14:01 UTC, bsian03 commented on tmp.js
> +client.connect();
delet

2022-05-23 14:01 UTC, bsian03 commented on tmp.ts
> +		po
po

2022-05-23 14:08 UTC, DonovanDMC commented on lib/Client.js
> +        }
do you want me to also remove checks for things like `commandID`?

2022-05-23 14:09 UTC, bsian03 commented on lib/Client.js
> +        }
yes please

2022-05-24 13:07 UTC, coolcalcacol requested changes

2022-05-24 13:07 UTC, coolcalcacol commented on index.d.ts
> +  type InteractionDataOption<T extends keyof Constants["ApplicationCommandOptionTypes"], V = unknown> = InteractionDataOptionsBase<Constants["ApplicationCommandOptionTypes"][T], V>;
```suggestion
  type InteractionDataOption<T extends Exclude<keyof Constants["ApplicationCommandOptionTypes"], "SUB_COMMAND" | "SUB_COMMAND_GROUP">, V = boolean | number | string> = InteractionDataOptionsBase<Constants["ApplicationCommandOptionTypes"][T], V>;
```
since `InteractionDataOption` is only ever referenced where a value is present?

2022-06-09 15:33 UTC, SagnikPradhan commented on index.d.ts
> +    dmPermission?: string | null;
```suggestion
    dmPermission?: boolean;
```

2022-06-09 15:40 UTC, SagnikPradhan commented on index.d.ts
> +    edit(options: Omit<T extends "CHAT_INPUT" ? ChatInputApplicationCommand : T extends "USER" ? UserApplicationCommand : T extends "MESSAGE" ? MessageApplicationCommand : never, "type">): Promise<th
```suggestion
    edit(options: Omit<T extends "CHAT_INPUT" ? ChatInputApplicationCommandStructure : T extends "USER" ? UserApplicationCommandStructure : T extends "MESSAGE" ? MessageApplicationCommandStructure : never, "type">): Promise<this>;
```

2022-06-09 17:52 UTC, SagnikPradhan commented on index.d.ts
> +    type: T;
```suggestion
    type: Constants["ApplicationCommandTypes"][T];
```
`T` is `"CHAT_INPUT" | "USER" | "MESSAGE"`, it should the value of enum not key

2022-07-05 16:46 UTC, DonovanDMC commented
Don't mind the force pushing mess, I somehow managed to cherry pick the new dev commits instead of merging them some time back, they've been properly merged in now

2022-08-29 00:30 UTC, closed without merging