fix(Member): Parse Member#premiumSince to timestamp
abalabahaha/eris pull request #1318
Opened 2021-12-21 00:07 UTC by bsian03

Fixes #1316

2021-12-21 00:17 UTC, DonovanDMC commented
`premium_since` is defined as both optional & nullable in the docs, optional is handled, nullable is not -- this results in NaN

2021-12-21 00:34 UTC, bsian03 commented
What if you don't want a number smh

2021-12-21 01:11 UTC, Catboi8 commented
in that case perfect because it is not

2021-12-21 10:48 UTC, danny-may commented
From what im reading in the docs, cant the value be `null`, `undefined` or a string? Shouldnt the type guard be a nullish check or a `typeof x === 'string'` check?

2021-12-21 10:50 UTC, bsian03 commented
But.. we already have an undefined check

2021-12-21 10:50 UTC, danny-may commented on lib/structures/Member.js
> +            this.premiumSince = data.premium_since === null ? null : Date.parse(data.premium_since);
```suggestion
            this.premiumSince = data.premium_since == null ? null : Date.parse(data.premium_since);
```

2021-12-21 10:50 UTC, danny-may commented
Ah, on the lines above, I missed that. Ignore me :)

2022-05-11 04:22 UTC, DonovanDMC submitted a review, later dismissed

2022-05-27 10:17 UTC, DonovanDMC requested changes
typings (both Member & OldMember)

2022-05-27 15:16 UTC, DonovanDMC approved these changes

2022-05-27 15:17 UTC, merged