add/fix options on client.editChannel
abalabahaha/eris pull request #1319
Opened 2021-12-28 02:33 UTC by aicushman

Corrects the option key for "video_quality_mode" and adds option key "permission_overwrites" per the `PATCH /channels/{channel.id}` endpoint spec at https://discord.com/developers/docs/resources/channel#modify-channel

This commit does NOT fix the types associated with the modified function.

2021-12-28 02:36 UTC, DonovanDMC commented
> This commit does NOT fix the types associated with the modified function.

the types are your responsibility when making a pull request

2021-12-28 02:37 UTC, DonovanDMC commented on lib/Client.js
> +            permission_overwrites:options.permissionOverwrites,
```suggestion
            permission_overwrites: options.permissionOverwrites,
```

2021-12-28 03:18 UTC, aicushman commented
> > This commit does NOT fix the types associated with the modified function.
> 
> the types are your responsibility when making a pull request

Happy to, if I knew the drill for editing the index.d.ts file. 
My assumption was it'd be faster for a reviewer to do it than to explain it, but either works for me 👍

In any case, AFAIK all that needs to happen is
`- interface EditChannelOptions extends Omit<CreateChannelOptions, "permissionOverwrites" | "reason">`
`+ interface EditChannelOptions extends Omit<CreateChannelOptions, "reason">`

2022-01-01 23:47 UTC, bsian03 requested changes, later dismissed
Docs and object in alphabetical order please, also please do typings. Feel free to join the Discord server if you're confused about typings

2022-06-08 05:33 UTC, DonovanDMC approved these changes

2022-06-08 05:37 UTC, merged