feat(permissions): Slash Permissions v2
abalabahaha/eris pull request #1372
Opened 2022-05-07 12:27 UTC by coolcalcacol

Remove bulk editing of command permissions as the endpoint has been disabled, 
add defaultMemberPermissions and DMPermission in place of defaultPermission, 
add the applicationCommandPermissionsUpdate gateway event, 
add the ApplicationCommandPermissionTypes channel type, 
modify createGuildCommand to return without the new DMPermission field

2022-05-09 03:10 UTC, DonovanDMC requested changes
keys should be camel cased

2022-05-09 03:10 UTC, DonovanDMC commented on index.d.ts
> +    DMPermission?: boolean;
```suggestion
    dmPermission?: boolean;
```
keys should be camel cased

2022-05-09 03:10 UTC, DonovanDMC commented on index.d.ts
> +    createGuildCommand(guildID: string, command: Omit<ApplicationCommandStructure, 'DMPermission'>): Promise<Omit<ApplicationCommand, 'DMPermission'>>;
```suggestion
    createGuildCommand(guildID: string, command: Omit<ApplicationCommandStructure, 'dmPermission'>): Promise<Omit<ApplicationCommand, 'dmPermission'>>;
```
keys should be camel cased

2022-05-09 03:10 UTC, DonovanDMC commented on lib/Client.js
> +        command.dm_permission = command.DMPermission;
```suggestion
        command.dm_permission = command.dmPermission;
```
keys should be camel cased

2022-05-09 03:10 UTC, DonovanDMC commented on lib/Client.js
> +    * @arg {Boolean} [command.DMPermission] The default role permissions
```suggestion
    * @arg {Boolean} [command.dmPermission] The default role permissions
```
keys should be camel cased

2022-05-09 20:51 UTC, bsian03 requested changes, later dismissed

2022-05-09 20:51 UTC, bsian03 commented on lib/gateway/Shard.js
> +                 * @prop {GuildApplicationCommandPermissions} GuildApplicationCommandPermissions The updated command permissions
event prop names should be camelCase

2022-05-11 04:16 UTC, DonovanDMC commented on index.d.ts
> +    createGuildCommand(guildID: string, command: Omit<ApplicationCommandStructure, 'dmPermission'>): Promise<Omit<ApplicationCommand, 'dmPermission'>>;
```suggestion
    createGuildCommand(guildID: string, command: Omit<ApplicationCommandStructure, "dmPermission">): Promise<Omit<ApplicationCommand, "dmPermission">>;
```

2022-05-20 21:08 UTC, DonovanDMC requested changes
jsdoc hasn't been changed for `Client#createGuildCommand`

2022-05-20 21:14 UTC, DonovanDMC requested changes
`bulkEditCommands`/`bulkEditGuildCommands` does not properly replace the camel cased names with underscored names

2022-05-20 21:18 UTC, DonovanDMC requested changes
`editCommand` / `editGuildCommand` also have not been modified

2022-05-21 23:21 UTC, DonovanDMC commented on index.d.ts
> +    applicationCommandPermissionsUpdate: [applicationCommandPermissions: GuildApplicationCommandPermissions]
```suggestion
    applicationCommandPermissionsUpdate: [applicationCommandPermissions: GuildApplicationCommandPermissions];
```

2022-05-22 23:26 UTC, DonovanDMC requested changes
consistent spacing (github isn't displaying it, but the newline after should also be removed)

2022-05-22 23:26 UTC, DonovanDMC commented on lib/Client.js
> +
```suggestion
        command.default_member_permissions = command.defaultMemberPermissions;
        command.dm_permission = command.dmPermission;
```

2022-05-22 23:26 UTC, DonovanDMC commented on lib/Client.js
> +
```suggestion
        command.default_member_permissions = command.defaultMemberPermissions;
```

2022-05-23 00:05 UTC, DonovanDMC approved these changes, later dismissed

2022-07-19 17:35 UTC, bsian03 requested changes
Audit log handling missing

2022-07-19 17:35 UTC, bsian03 commented on lib/Client.js
> +    * @arg {String?} [command.defaultMemberPermissions] The default member [permissions](https://discord.com/developers/docs/topics/permissions) represented as a bit set
As below

2022-07-19 17:35 UTC, bsian03 commented on lib/Client.js
> +    * @arg {String?} [command.defaultMemberPermissions] The default member [permissions](https://discord.com/developers/docs/topics/permissions) represented as a bit set
As above

2022-07-19 17:35 UTC, bsian03 commented on lib/Client.js
> +    * @arg {String?} [command.defaultMemberPermissions] The default member [permissions](https://discord.com/developers/docs/topics/permissions) represented as a bit set
As above

2022-07-19 17:35 UTC, bsian03 commented on lib/structures/Guild.js
> +    * @arg {String?} [command.defaultMemberPermissions] The default member [permissions](https://discord.com/developers/docs/topics/permissions) represented as a bit set
As below

2022-07-19 17:35 UTC, bsian03 commented on lib/structures/Guild.js
> +    * @arg {String?} [command.defaultMemberPermissions] The default member [permissions](https://discord.com/developers/docs/topics/permissions) represented as a bit set
As below

2022-07-19 17:35 UTC, bsian03 commented on lib/Client.js
> +    * @arg {String?} [command.defaultMemberPermissions] The default member [permissions](https://discord.com/developers/docs/topics/permissions) represented as a bit set
As above

2022-07-19 17:35 UTC, bsian03 commented on index.d.ts
> +    defaultMemberPermissions?: string;
Should be able to pass BigInt/Number/String/Permission to be consistent with other permission related methods elsewhere

2022-08-28 14:44 UTC, bsian03 requested changes

2022-08-28 14:44 UTC, bsian03 commented on lib/Client.js
> +                command.defaultMemberPermissions = command.defaultMemberPermissions instanceof Permission ? String(command.defaultMemberPermissions.allow) : String(command.defaultMemberPermissions);
This seems kinda useless

2022-08-28 14:44 UTC, bsian03 commented on lib/Client.js
> +                command.defaultMemberPermissions = command.defaultMemberPermissions instanceof Permission ? String(command.defaultMemberPermissions.allow) : String(command.defaultMemberPermissions);
Same with here

2022-08-28 14:44 UTC, bsian03 commented on lib/Client.js
> +    * @arg {bigint | number | string | Permission?} [command.defaultMemberPermissions] The default member [permissions](https://discord.com/developers/docs/topics/permissions) represented as a bit se
```suggestion
    * @arg {BigInt | Number | String | Permission?} [command.defaultMemberPermissions] The default member [permissions](https://discord.com/developers/docs/topics/permissions) represented as a bit set
```

2022-08-28 14:44 UTC, bsian03 commented on lib/Client.js
> +     * @returns {Promise<Object>} Resolves with a commands object
```suggestion
    * @returns {Promise<Object>} Resolves with a commands object
```

2022-08-28 14:44 UTC, bsian03 commented on lib/Client.js
> +            command.defaultMemberPermissions = command.defaultMemberPermissions instanceof Permission ? String(command.defaultMemberPermissions.allow) : String(command.defaultMemberPermissions);
Same here

2022-08-28 14:44 UTC, bsian03 commented on lib/Client.js
> +    * @arg {bigint | number | string | Permission?} [command.defaultMemberPermissions] The default member [permissions](https://discord.com/developers/docs/topics/permissions) represented as a bit se
```suggestion
    * @arg {BigInt | Number | String | Permission?} [command.defaultMemberPermissions] The default member [permissions](https://discord.com/developers/docs/topics/permissions) represented as a bit set
```

2022-08-28 14:44 UTC, bsian03 commented on lib/Client.js
> +            command.defaultMemberPermissions = command.defaultMemberPermissions instanceof Permission ? String(command.defaultMemberPermissions.allow) : String(command.defaultMemberPermissions);
Same here

2022-08-28 14:44 UTC, bsian03 commented on lib/Client.js
> +    * @arg {bigint | number | string | Permission?} [command.defaultMemberPermissions] The default member [permissions](https://discord.com/developers/docs/topics/permissions) represented as a bit se
```suggestion
    * @arg {BigInt | Number | String | Permission?} [command.defaultMemberPermissions] The default member [permissions](https://discord.com/developers/docs/topics/permissions) represented as a bit set
```

2022-08-28 14:44 UTC, bsian03 commented on lib/Client.js
> +     * @returns {Promise<Object>} Resolves with a commands object
```suggestion
    * @returns {Promise<Object>} Resolves with a commands object
```

2022-08-28 14:44 UTC, bsian03 commented on lib/Client.js
> +            command.defaultMemberPermissions = command.defaultMemberPermissions instanceof Permission ? String(command.defaultMemberPermissions.allow) : String(command.defaultMemberPermissions);
Same here

2022-08-28 14:44 UTC, bsian03 commented on lib/Client.js
> +    * @arg {bigint | number | string | Permission?} [command.defaultMemberPermissions] The default member [permissions](https://discord.com/developers/docs/topics/permissions) represented as a bit se
```suggestion
    * @arg {BigInt | Number | String | Permission?} [command.defaultMemberPermissions] The default member [permissions](https://discord.com/developers/docs/topics/permissions) represented as a bit set
```

2022-08-28 14:44 UTC, bsian03 commented on lib/Client.js
> +            command.defaultMemberPermissions = command.defaultMemberPermissions instanceof Permission ? String(command.defaultMemberPermissions.allow) : String(command.defaultMemberPermissions);
Same here

2022-08-28 14:44 UTC, bsian03 commented on lib/gateway/Shard.js
> +                 * @prop {GuildApplicationCommandPermissions} guildApplicationCommandPermissions The updated command permissions
```suggestion
                 * @prop {Object} guildApplicationCommandPermissions The updated command permissions
```
Can't use typescript interfaces in JSDoc

2022-08-28 14:46 UTC, bsian03 commented on lib/structures/Guild.js
> +    * @arg {String?} [command.defaultMemberPermissions] The default member [permissions](https://discord.com/developers/docs/topics/permissions) represented as a bit set
This wasn't updated

2022-08-28 14:46 UTC, bsian03 commented on lib/structures/Guild.js
> +    * @arg {String?} [command.defaultMemberPermissions] The default member [permissions](https://discord.com/developers/docs/topics/permissions) represented as a bit set
This wasn't updated

2024-01-05 14:46 UTC, bsian03 requested changes
Starting to consider whether its worth having a separate ApplicationCommand class within Eris...

2024-01-05 14:46 UTC, bsian03 commented on index.d.ts
> -    defaultPermission?: boolean;
This should be retained for deprecation in line with Discord

2024-01-05 14:46 UTC, bsian03 commented on index.d.ts
> +    dmPermission?: boolean;
~~These shold be snake_case, responses from Discord are being treated as is. Not sure why default_permission wasn't treated that way though...~~

2024-01-05 14:46 UTC, bsian03 commented on index.d.ts
> +    applicationCommandPermissionsUpdate: [applicationCommandPermissions: GuildApplicationCommandPermissions];
L256 `permissions` is a guaranteed property

2024-01-05 14:46 UTC, bsian03 commented on lib/structures/Guild.js
bulkEditCommandPermissions needs removing

2024-01-05 14:46 UTC, bsian03 commented on index.d.ts
> +    createGuildCommand(guildID: string, command: Omit<ApplicationCommandStructure, "dmPermission">): Promise<Omit<ApplicationCommand, "dmPermission">>;
Should be `dm_permission`, see other review

2024-01-05 14:46 UTC, bsian03 commented on index.d.ts
> +    defaultMemberPermissions?: bigint | number | string | Permission;
In incoming data, this is a nullable string only. In outgoing data, this is as handled in js code, but should also be nullable

2024-01-05 14:46 UTC, bsian03 commented on lib/Client.js
> +                command.defaultMemberPermissions = command.defaultMemberPermissions instanceof Permission ? String(command.defaultMemberPermissions.allow) : String(command.defaultMemberPermissions);
Should allow for nullable handling

2024-01-05 14:46 UTC, bsian03 commented on lib/Client.js
> +            command.default_member_permissions = command.defaultMemberPermissions;
This can be put in the unconditional check

2024-01-06 19:07 UTC, bsian03 commented
Am redoing how application commands are handled so don't touch for now pls

2024-01-09 21:58 UTC, bsian03 approved these changes

2024-01-09 21:59 UTC, merged