fix(getMessages): Emit "error" with type `Error`
abalabahaha/eris pull request #1387
Opened 2022-06-16 17:36 UTC by frobinsonj

Didn't really know how to title this, apologies if I got it wrong.

Error event `err` param should be type `Error` - https://github.com/abalabahaha/eris/blob/dev/index.d.ts#L711

2022-06-17 00:20 UTC, DonovanDMC commented
It would probably be better to construct the error object, then overwrite the stack
Or even just override the message of the caught error then emit it rather than both making a new error object & emitting the original stack

2022-06-17 00:22 UTC, DonovanDMC commented on lib/Client.js
> +                this.emit("error", new Error(`Error creating message from channel messages\n${err.stack}\n${JSON.stringify(messages)}`));
```suggestion
                err.message = `Error creating message from channel messages\n${JSON.stringify(messages)}`;
                this.emit("error", err);
```

2022-06-17 19:40 UTC, DonovanDMC approved these changes

2022-06-17 19:43 UTC, DonovanDMC requested changes
[options.cause](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Error) was added in node 16.9.0, we're currently on v10 (v14 at the latest), so we cannot use it

2022-06-18 15:21 UTC, frobinsonj commented
> [options.cause](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Error) was added in node 16.9.0, we're currently on v10 (v14 at the latest), so we cannot use it

Went with your original suggestion. Thanks.

2022-06-18 15:30 UTC, DonovanDMC approved these changes

2022-06-18 22:23 UTC, abalabahaha requested changes
Setting `.message` doesn't affect `.stack`. TBH I don't think the full JSON belongs in the error message. `warn` (also not great) and `debug` events are used to log JSON for other parsing errors

2022-06-18 22:25 UTC, DonovanDMC commented
We can slice the first line off the stack and remake it with the new message

2024-01-05 14:56 UTC, bsian03 commented
Any other alternatives to this? Current solution (although error might be hard to read) is the best one imo

2024-07-12 14:22 UTC, closed without merging