Fix typo for RawRESTRequest
abalabahaha/eris pull request #1401
Opened 2022-08-01 15:26 UTC by flav28

2022-08-09 20:03 UTC, DonovanDMC requested changes

2022-08-09 20:03 UTC, DonovanDMC commented on index.d.ts
> +    thumbnail?: EmbedImage;
This is not a typo. Undo this.

2022-08-16 19:02 UTC, DonovanDMC commented on index.d.ts
> +    thumbnail?: EmbedImage;
Don't resolve this without actually doing what was asked.

2022-11-18 11:39 UTC, bsian03 requested changes
Fix the comment please

2024-01-05 15:05 UTC, bsian03 approved these changes

2024-01-05 15:07 UTC, merged