Alphabetize properties in JS/TS docs and fix typos
abalabahaha/eris pull request #1466
Opened 2024-01-08 21:30 UTC by iiFDCT

Don't mind me farming. Stuff not being alphabetized in some areas, but then alphabetized in other areas is annoying to me

 - Alphabetize properties functions in JS & TS docs
 - Minor typo fixes

2024-01-12 11:29 UTC, bsian03 requested changes

2024-01-12 11:29 UTC, bsian03 commented on lib/gateway/Shard.js
>                  * @prop {Boolean?} oldMember.pending Whether the member has passed the guild's Membership Screening requirements
```suggestion
                * @prop {Boolean?} oldMember.pending Whether the member has passed the guild's Membership Screening requirements
                * @prop {Number?} oldMember.premiumSince Timestamp of when the member boosted the guild
```

2024-01-12 11:29 UTC, bsian03 commented on lib/rest/Endpoints.js
>  module.exports.COMMAND_PERMISSIONS =         (applicationID, guildID, commandID) => `/applications/${applicationID}/guilds/${guildID}/commands/${commandID}/permissions`;
```suggestion
module.exports.COMMAND_PERMISSIONS =         (applicationID, guildID, commandID) => `/applications/${applicationID}/guilds/${guildID}/commands/${commandID}/permissions`;
module.exports.COMMANDS =                                        (applicationID) => `/applications/${applicationID}/commands`;
```

2024-01-12 11:29 UTC, bsian03 commented on lib/rest/Endpoints.js
user connections and user connection platform on L100/101 need to be switched

2024-01-12 11:29 UTC, bsian03 commented on lib/structures/Guild.js
> +    * @arg {String} commandID The command id
```suggestion
    * @arg {String} commandID The command ID
```

2024-01-12 11:29 UTC, bsian03 commented on lib/structures/Message.js
>  * @prop {User} interaction.user The user who invoked the interaction
Missed all of these :)

2024-01-12 11:29 UTC, bsian03 commented on index.d.ts
> +  export type ChannelTypeConversion<T extends GuildChannelTypes> =
```suggestion
  type ChannelTypeConversion<T extends GuildChannelTypes> =
```

2024-01-12 11:29 UTC, bsian03 commented on index.d.ts
Can you go through references and TS errors in this file, you messed up the merge conflict. Anything that throws an error (e.g. Application Command) where the reference has had a recent change should be removed (though please double check before you do)

2024-01-12 15:50 UTC, iiFDCT commented on index.d.ts
The only errors in the TS file are from another PR afaik, like the one shown in my screenshot here. I fixed anything that I broke with my merge commit already (such as all of the interaction classes being duplicate)
![image](https://github.com/abalabahaha/eris/assets/35053522/ab7cf43a-c29b-4542-be02-d3d049f83b5a)

2024-01-12 16:14 UTC, iiFDCT commented
@bsian03 Should be good on the typings side of things. Cleared the last errors up now

2024-01-13 16:23 UTC, bsian03 approved these changes

2024-01-13 16:24 UTC, merged