feat(User): Support avatar decorations
abalabahaha/eris pull request #1471
Opened 2024-01-14 19:53 UTC by iiFDCT

Adds support for user avatar decorations. Avatar decoration properties will also exist within members, to be consistent with other user properties that do the same.

You may notice that some of the properties aren't the same as what's shown on the Discord docs rn. Discord have changed the field names and CDN endpoint for avatar decorations apparently so I used discord/discord-api-docs#6464 to make this PR so I wouldnt have to potentially go back and make changes lol

I'm sure I probably made a mistake in TS docs so any help would be great if you happen to spot any

2024-01-21 18:30 UTC, bsian03 requested changes
Please lint, merge conflict resolution is invalid

2024-01-23 00:29 UTC, bsian03 requested changes

2024-01-23 00:29 UTC, bsian03 commented on lib/structures/User.js
Include in JSON please

2024-01-23 16:41 UTC, iiFDCT commented on lib/structures/User.js
Done 👍🏻

2024-01-28 00:05 UTC, bsian03 approved these changes

2024-01-28 00:06 UTC, merged