feat(Guild): Edit MFA level
abalabahaha/eris pull request #1473
Opened 2024-01-17 16:47 UTC by iiFDCT

2024-01-19 00:00 UTC, bsian03 requested changes
lgtm otherwise

2024-01-19 00:00 UTC, bsian03 commented on index.d.ts
> +    editGuildMFALevel(guildID: string, level: 0 | 1, reason?: string): Promise<number>;
`level` should have its own type

2024-01-19 01:13 UTC, bsian03 commented on index.d.ts
> +    editGuildMFALevel(guildID: string, level: 0 | 1, reason?: string): Promise<number>;
Constant, not type

2024-01-19 20:10 UTC, iiFDCT commented on index.d.ts
> +    editGuildMFALevel(guildID: string, level: 0 | 1, reason?: string): Promise<number>;
Whoopsie, fixed

2024-01-21 19:23 UTC, bsian03 requested changes
API actually returns `{ level: number }`. Also please specify that the bot needs to be the guild owner for it to work

2024-01-22 01:10 UTC, bsian03 commented
Tested on 5da4537, no actual code changes since https://github.com/iiFDCT/eris/compare/5da4537...6bcbb02 - Shard and createGuild edits are PR merges.
Will merge once I get to test typings

2024-01-22 20:42 UTC, bsian03 requested changes

2024-01-22 20:42 UTC, bsian03 commented on index.d.ts
> +    level: MFALevel
```suggestion
    level: MFALevel;
```

2024-01-22 20:42 UTC, bsian03 approved these changes

2024-01-22 20:42 UTC, merged