feat(Role): Role flags
abalabahaha/eris pull request #1474
Opened 2024-01-17 17:18 UTC by iiFDCT

[Docs reference](https://discord.com/developers/docs/topics/permissions#role-object-role-flags)

Will probably update the role tags in this PR too unless Bsian tells me otherwise. Eris is missing the 3 newer role tags atm

2024-01-28 00:19 UTC, bsian03 requested changes

2024-01-28 00:19 UTC, bsian03 commented on lib/structures/Role.js
Needs handling for null available_for_purchase and guild_connections

2024-01-29 17:41 UTC, iiFDCT commented on lib/structures/Role.js
Fixed 👍🏻

2024-02-04 19:53 UTC, bsian03 commented on lib/Constants.js
> +}
```suggestion
};
```

2024-02-04 19:56 UTC, bsian03 approved these changes

2024-02-04 19:57 UTC, merged