feat(VoiceChannel): Support voice channel statuses
abalabahaha/eris pull request #1496
Opened 2024-04-21 01:56 UTC by iiFDCT

# Support voice channel statuses

#### Refs:
[Document set voice channel status discord/discord-api-docs#6398](https://github.com/discord/discord-api-docs/pull/6398)
[Document Set Voice Channel Status endpoint discord/discord-api-docs#6400](https://github.com/discord/discord-api-docs/pull/6400)

Will do TS docs when PR is finalised. Waiting on Bsian to advise on the `voiceChannelStatusUpdate` event

2024-04-24 15:27 UTC, flav-code commented
Works fine on my side
- Edit
- GuildCreate

2024-05-01 00:33 UTC, flav-code commented
@bsian03

2024-05-01 00:43 UTC, bsian03 commented
I'm aware, I haven't had the chance to look at this yet

2024-05-04 10:02 UTC, flav-code commented
Maybe set the status property to null if not set like the packet sent by discord

2024-06-09 17:42 UTC, bsian03 commented
I'm not 100% sure when discord will merge the PRs, so please complete with TS docs so I can preapprove and merge when Discord merge (or when I get impatient, whichever comes first)

2024-06-09 19:22 UTC, iiFDCT commented
> I'm not 100% sure when discord will merge the PRs, so please complete with TS docs so I can preapprove and merge when Discord merge (or when I get impatient, whichever comes first)

This PR will be finalised when you let me know what you want me to do with the `voiceChannelStatusUpdate` event. You told me in dms you'd have a think about it but never got back to me hence it's still a draft 👍🏻

2024-06-09 19:31 UTC, bsian03 commented
Ah, sorry. Yeah emit a separate event for it

2024-07-12 15:13 UTC, bsian03 requested changes

2024-07-12 15:13 UTC, bsian03 commented on lib/Client.js
> +     * Set the status of a voice channel
Probably worth noting that this will not work in stage channels since stage channel docs will inherit voice channel docs

2024-07-12 15:13 UTC, bsian03 commented on lib/gateway/Shard.js
> +                });
No need to spread channel update or even to reassign `channel` here, it'll check if the props exist anyways.

2024-07-20 14:52 UTC, bsian03 approved these changes

2024-07-20 14:52 UTC, merged