handle stage messages
abalabahaha/eris pull request #1501
Opened 2024-05-04 09:08 UTC by flav-code

2024-05-07 21:39 UTC, iiFDCT approved these changes

2024-06-09 18:00 UTC, bsian03 requested changes
Just this small bold topic change text. Also will consult abal about that content reassignment since we're directly replacing data from discord.
otherwise LGTM

2024-06-09 18:00 UTC, bsian03 commented on lib/structures/Message.js
> +                data.content = `${this.author.mention} changed the Stage topic: ${this.content}`;
```suggestion
                data.content = `${this.author.mention} changed the Stage topic: **${this.content}**`;
```

2024-06-09 18:01 UTC, flav-code commented on lib/structures/Message.js
> +                data.content = `${this.author.mention} changed the Stage topic: ${this.content}`;
![image](https://github.com/abalabahaha/eris/assets/48295189/05200313-05eb-442b-ba3b-4106da7d4320)

2024-06-12 23:52 UTC, bsian03 commented
we decided the best way moving forward would be to remove all system localisation message handling, i.e. we will not be setting the message content if a particular message type required it

2024-06-13 00:02 UTC, flav-code commented
you want me to remove all data.content from message system ?

2024-06-13 00:04 UTC, bsian03 commented
correct, the only thing that should be in content is what's reflected on discord

2024-06-13 00:07 UTC, MCausc78 commented
Personally I would make a getter like `displayedContent` or `systemContent` rather replacing data.content

2024-06-13 00:08 UTC, flav-code commented
> Personally I would make a getter like `displayedContent` or `systemContent` rather replacing data.content

I agree

2024-06-13 00:10 UTC, bsian03 commented
neither of us saw a legitimate and proper use case for having localised system messages in the message content. I'm happy for you to discuss this with me on discord though.

2024-06-21 04:58 UTC, flav-code commented
we could even do away with the user's call function, thus eliminating this unnecessary switching case

2024-06-22 11:44 UTC, bsian03 commented
I'll work on that, the PR is massively out of date so I'll have to look over everything again but it's on my list of things to do asap

2024-07-08 10:32 UTC, bsian03 approved these changes

2024-07-08 10:34 UTC, merged