fix(Member): Voice state not added when the bot starts
abalabahaha/eris pull request #1525
Opened 2024-08-08 13:22 UTC by babiabeo

Fix: #1522

Currently, the voice state is only updated if the data has `member` field. However, the `member` field is optional in [Voice State object](https://discord.com/developers/docs/resources/voice#voice-state-object-voice-state-structure), leading to incorrect update handling. This PR ensures that the voice state is updated even when the `member` field is not present.

2024-08-08 13:52 UTC, bsian03 commented
Thanks for getting this - will review and test soon
cc @flav-code

2024-08-08 14:06 UTC, TTtie approved these changes
From my very brief local testing, it seems to be working, both at startup and while the voice state is updated with the new member data!

2024-08-08 14:29 UTC, TTtie commented on lib/structures/Member.js
> +            if(data.hasOwnProperty("member")){
a very small style nit I just noticed, there should be a space between the if condition and the block inside
```suggestion
            if(data.hasOwnProperty("member")) {
```

2024-08-10 17:25 UTC, flav-code commented
LGTM

2024-08-10 17:32 UTC, flav-code requested changes
Style

2024-08-10 17:33 UTC, flav-code commented
![image](https://github.com/user-attachments/assets/ca97921f-ee3b-4598-abe5-9556fd59b68e)

2024-08-10 17:37 UTC, babiabeo commented
It is weird that the linter doesn't detect that one.

2024-08-17 21:28 UTC, bsian03 commented
Will fix the linter, otherwise lgtm

2024-08-17 21:28 UTC, merged