Add support for shard latency checking
abalabahaha/eris pull request #155
Opened 2017-01-06 09:40 UTC by Brayzure

- Each shard now stores the last time it sent a heartbeat, and when it was last acknowledged
- Shard getter returns latency if both values exist

2017-01-06 13:06 UTC, hsiW requested changes
Forgot to add docs for new things

2017-01-06 17:47 UTC, hsiW approved these changes

2017-01-08 09:39 UTC, abalabahaha requested changes

2017-01-08 09:39 UTC, abalabahaha commented on lib/gateway/Shard.js
> +        return this.lastHeartbeatSent && this.lastHeartbeatReceived ? this.lastHeartbeatReceived - this.lastHeartbeatSent : null;
`null` should probably be a JS number. Maybe `Infinity`?

2017-01-08 09:39 UTC, abalabahaha commented on lib/gateway/Shard.js
> +* @prop {Number} lastHeartbeatSent Timestamp when shard last sent a heartbeat
Wording is a bit awkward for these

2017-01-08 09:48 UTC, Brayzure commented on lib/gateway/Shard.js
> +* @prop {Number} lastHeartbeatSent Timestamp when shard last sent a heartbeat
Yeah, I thought it was, but I couldn't figure out a better way to word it. Ideas?

2017-01-08 09:54 UTC, Brayzure commented on lib/gateway/Shard.js
> +        return this.lastHeartbeatSent && this.lastHeartbeatReceived ? this.lastHeartbeatReceived - this.lastHeartbeatSent : null;
`Infinity` would certainly work, but I'm wondering if there's a better way to signify that the value the user is asking for doesn't make sense.

2017-01-09 01:26 UTC, hsiW approved these changes

2017-01-09 01:30 UTC, abalabahaha approved these changes

2017-01-09 01:30 UTC, merged