Add application to client options in constructor
abalabahaha/eris pull request #1583
Opened 2024-12-20 14:23 UTC by someramsey

`Client.application` should be configurable from the constructor. This pull request just adds application property to the options inside the Client constructor.

2024-12-20 14:35 UTC, retrouser955 reviewed
Please add JSDoc for the option

2024-12-20 14:38 UTC, retrouser955 commented on index.d.ts
> +    application?: { id: string; flags?: number };
This needs to be sorted alphabetically

2024-12-22 18:23 UTC, someramsey commented
Bump

2025-09-27 22:03 UTC, bsian03 requested changes

2025-09-27 22:03 UTC, bsian03 commented on lib/Client.js
> +        flags: options.application.flags ?? 0,
This is not backwards compatible

2025-09-27 22:03 UTC, bsian03 commented on lib/Client.js
> +   * @arg {Object} [options.application] Object containing the bot application's ID and its public flags
Need to document child properties

2025-09-27 22:24 UTC, bsian03 commented on index.d.ts
> +    application?: { id: string; flags?: number };
Props also need to be sorted

2025-09-27 22:28 UTC, someramsey commented on lib/Client.js
> +        flags: options.application.flags ?? 0,
Ah. Anyways I made this commit ages ago. I don't even remember what its about anymore. So I wont be pushing any further changes here you can close it

2025-10-06 11:31 UTC, closed without merging