Voice and Client bug fixes
abalabahaha/eris pull request #161
Opened 2017-01-09 21:21 UTC by briantanner

- Fix 'channels' of undefined in Client.getMessage
- Remove inconsistent promise rejection in leaveVoiceChannel
- Fix undefined pending guilds in readyHandler and disconnectHandler in VoiceConnectionManager

2017-01-09 21:26 UTC, briantanner commented
The voice stuff may need looking at further

2017-01-09 22:12 UTC, brussell98 requested changes

2017-01-09 22:12 UTC, brussell98 commented on lib/Client.js
> +        const guildID = this.channelGuildMap[channelID];
This seems to be uneeded

2017-01-09 22:15 UTC, briantanner commented on lib/Client.js
> +        const guildID = this.channelGuildMap[channelID];
Ahh right, thanks for pointing it out

2017-01-15 09:04 UTC, abalabahaha commented
Its probably better to figure out why channelGuildMap has data for guilds that don't appear to exist, rather than checking for null/undefined there

2017-01-15 09:06 UTC, merged