Add guildMemberChunk Event
abalabahaha/eris pull request #169
Opened 2017-01-20 20:03 UTC by Fuechschen

This adds an event when discord sends new members on startup or while caching new guilds.

This is especially useful if you want to add the users to a database. Since guildCreate is able to fire before all users are cached, it can lead to errors on new guilds when not all users are passed in guild.members and, after you added them to your database, you try to query for non-existent users.

2017-01-20 20:11 UTC, abalabahaha requested changes

2017-01-20 20:11 UTC, abalabahaha commented on lib/gateway/Shard.js
> +                 * Fired when discord sends members on startup
Awkward wording. Maybe something like `Fired when Discord sends member chunks`

This also isn't limited to just startup

2017-01-20 20:15 UTC, hsiW approved these changes

2017-01-21 01:23 UTC, abalabahaha approved these changes

2017-01-21 01:23 UTC, merged