added typings
abalabahaha/eris pull request #341
Opened 2017-12-15 18:58 UTC by DusterTheFirst

ready and disconnect events from the client were missing

2017-12-15 19:32 UTC, aurieh commented
You also have to implement the ready event in Client and Shard classes, as `Emittable` is an interface.

2017-12-18 20:04 UTC, DusterTheFirst commented
bump?

2017-12-18 21:31 UTC, abalabahaha commented
Trying to find a Typescript user to review :|

2017-12-18 22:12 UTC, aurieh requested changes

2017-12-18 22:12 UTC, aurieh commented on index.d.ts
> -  interface Connection {
Was this intentional?

2017-12-18 23:20 UTC, DusterTheFirst commented on index.d.ts
> -  interface Connection {
no

2017-12-19 01:16 UTC, merged