Add permissionOverwrites option when creating guild channels
abalabahaha/eris pull request #544
Opened 2019-10-15 09:08 UTC by Astraeus-

Adds the option to specify an array of overwrite objects to be applied when creating a guild channel as specified in the [Discord API Documentation](https://discordapp.com/developers/docs/resources/guild#create-guild-channel).

I'm not experienced with writing typings for TypeScript, so I did not update any of those.

2019-10-15 10:04 UTC, abalabahaha requested changes
Has this been tested? I'd expect this to fail because `PermissionOverwrite#toJSON()` omits the ID...

2019-10-15 10:04 UTC, abalabahaha commented on lib/Client.js
> +    * @arg {Array} [options.permissionOverwrites] An array containing overwrite objects
Would be better to explicitly state "permission overwrite objects"

2019-10-15 10:52 UTC, Astraeus- commented
I tested creating a channel with permission overwrites specified as per the [Discord docs](https://discordapp.com/developers/docs/resources/channel#overwrite-object) and it worked as expected.

2019-10-18 12:21 UTC, abalabahaha commented
Ah, you meant raw overwrite objects.

2019-10-18 12:24 UTC, merged