Fix typings typos
abalabahaha/eris pull request #560
Opened 2019-11-18 06:39 UTC by Skillz4Killz

This PR fixes 2 more typos in the typings.

1. Overwrite types are `member` and `role`.
2. fields `name` and `value` are mandatory and can not be optional.

2019-11-18 07:31 UTC, DonovanDMC commented
Always make PRs into the dev branch

2019-11-18 13:55 UTC, DonovanDMC submitted a review, later dismissed

2019-11-20 17:58 UTC, abalabahaha requested changes

2019-11-20 17:58 UTC, abalabahaha commented on lib/structures/GuildChannel.js
> +    * @arg {Boolean} [options.nsfw] The nsfw status of the channel (guild channels only)
The last bit is unnecessary, this is the `GuildChannel` class

2019-11-20 18:11 UTC, abalabahaha submitted a review, later dismissed

2019-11-20 18:15 UTC, abalabahaha approved these changes

2019-11-20 18:17 UTC, merged