Adds support for new audit log events
abalabahaha/eris pull request #562
Opened 2019-11-19 18:32 UTC by Khaazz

This updates eris according to discordapp/discord-api-docs#1191.

It adds:
```
MEMBER_MOVE: 26
MEMBER_DISCONNECT: 27
BOT_ADD: 28

MESSAGE_BULK_DELETE: 73
MESSAGE_PIN: 74
MESSAGE_UNPIN: 75

INTEGRATION_CREATE: 80
INTEGRATION_UPDATE: 81
INTEGRATION_DELETE: 82
```

This PR also updated the typings.

2019-11-19 18:39 UTC, Skillz4Killz submitted a review, later dismissed

2019-11-19 20:35 UTC, Skillz4Killz submitted a review, later dismissed

2019-11-20 18:10 UTC, abalabahaha requested changes
`GuildAuditLogEntry#target` getter needs to be updated to return null for integration actions

2019-11-21 18:16 UTC, Khaazz commented
Edit:s
For MEMBER_MOVE and MEMBER_DISCONNECT, the target getter now returns `null`. discord-api-docs#1195l
For INTEGRATION events, the target getter now returns `null`. discord-api-docs#1194
For INTEGRATION options specified in the issue, they are includes in `data.before` and `data.after` so we don't need to expose thoses directly.

I keep a server with integrations for testing if this changes in a near future

2019-11-21 23:55 UTC, abalabahaha requested changes

2019-11-21 23:55 UTC, abalabahaha commented on lib/structures/GuildAuditLogEntry.js
> +            if(this.actionType === 26 || this.actionType === 27) { // MEMBER_MOVE / MEMBER_DISCONNECT
Constants can be used here

2019-11-23 03:58 UTC, abalabahaha approved these changes

2019-11-23 03:59 UTC, merged