Adds new constants and unify Constants usage
abalabahaha/eris pull request #569
Opened 2019-11-23 21:42 UTC by Khaazz

This PR does a general code cleanup:
- removes hardcoded values for `channel.type` and `message.type`
- uniformises Constants usage in the lib (always destructure constants).
It renames usage of OPCode to `GatewayOPCodes` or `VoiceOPCodes` and makes it more explicit.

*updates typings with new constants*

2019-11-24 01:40 UTC, abalabahaha approved these changes

2019-11-24 01:44 UTC, abalabahaha requested changes

2019-11-24 01:44 UTC, abalabahaha commented on lib/Constants.js
> +    USER_PREMIUM_GUILD_SUBSCRIPTION_TIER_1:	9,
Hold on, are those tabs?

2019-11-24 01:44 UTC, abalabahaha commented on lib/Constants.js
> +    USER_PREMIUM_GUILD_SUBSCRIPTION_TIER_2:	10,
Yeah that's a tab

2019-11-24 01:44 UTC, abalabahaha commented on lib/Constants.js
> +    USER_PREMIUM_GUILD_SUBSCRIPTION_TIER_3:	11,
Use spaces

2019-11-24 07:20 UTC, Khaazz commented on lib/Constants.js
> +    USER_PREMIUM_GUILD_SUBSCRIPTION_TIER_1:	9,
nice catch, fixed

2019-11-24 09:55 UTC, Khaazz commented
Also uses ChannelTypes in Shard.js.

2019-11-25 23:04 UTC, abalabahaha approved these changes

2019-11-25 23:05 UTC, merged