Promisified Guild#fetchAllMembers
abalabahaha/eris pull request #576
Opened 2019-11-26 23:15 UTC by LJNeon

I did a basic test to make sure this works, more testing may or may not be useful.

2019-11-26 23:29 UTC, apacheli requested changes

2019-11-26 23:29 UTC, Apacheli commented on lib/gateway/Shard.js
> +                if(!this.requestMembersPromise.hasOwnProperty(guildID))
Missing curly

2019-11-26 23:30 UTC, LJNeon commented on lib/gateway/Shard.js
> +                if(!this.requestMembersPromise.hasOwnProperty(guildID))
Fixed

2019-12-01 01:44 UTC, abalabahaha requested changes

2019-12-01 01:44 UTC, abalabahaha commented on lib/gateway/Shard.js
> +                this.requestMembersPromise[guildID].res();
`.received` should be returned here too

2019-12-01 01:44 UTC, abalabahaha commented on lib/structures/Guild.js
> +    * @returns {Promise<Number>} Resolves with the total amount of fetched members.
Nit: `total number of`

2019-12-01 02:03 UTC, LJNeon commented on lib/structures/Guild.js
> +    * @returns {Promise<Number>} Resolves with the total amount of fetched members.
should be fixed

2019-12-01 02:04 UTC, LJNeon commented on lib/gateway/Shard.js
> +                this.requestMembersPromise[guildID].res();
should be fixed

2019-12-01 02:11 UTC, abalabahaha approved these changes

2019-12-01 02:12 UTC, merged