feat: add commandNotFound event
abalabahaha/eris pull request #582
Opened 2019-11-30 15:29 UTC by ItsANameToo

This PR adds a new event to the `CommandClient` called `commandNotFound`. It gets triggered when the CommandClient could not resolve the user's message to any of the existing commands. This offers the ability for developers to hook into this event to show a response to their users that it could not find a matching command. An example would be:

```
bot.on("commandNotFound", async (message) => {
  // can also inspect the message itself here as that gets passed along
  await message.channel.createMessage(`Sorry, that command does not exist`);
})
```

Unless I missed something, I could not find an existing way to have the bot handle non-existing commands when using the `CommandClient`.

2019-11-30 15:46 UTC, alex-taxiera requested changes
needs typings and jsdocs

2019-11-30 15:52 UTC, Khaazz commented
Also would be emitted on every message insteaf of "on every message that starts with the prefix but that are not an actual command"

2019-11-30 16:13 UTC, ItsANameToo commented
@Khaazz message prefix is checked before on this line: https://github.com/abalabahaha/eris/blob/master/lib/command/CommandClient.js#L143, so it should only be emitted on messages with the correct prefix but that call a non-existing command

2019-12-01 02:23 UTC, abalabahaha reviewed
Personally I'm not a fan of command not found messages. It gets spammy and essentially hogs the entire command range for a prefix. Thanks for the PR though.

2019-12-01 02:23 UTC, abalabahaha commented on lib/command/CommandClient.js
> +        } else {
Yeah, this should be on the previous line if you only wait it for valid prefixes. Currently this runs if the prefix does not match too.

2019-12-01 02:23 UTC, closed without merging