Fix Client#createGuild() bug where shard was undefined
abalabahaha/eris pull request #588
Opened 2019-12-03 03:21 UTC by Apacheli

This fixes 2 issues that were recently discovered in the Eris channel.

1. The first issue was that it was a race condition between `Guild#shard` and `Client#guildCreate`.
2. The second issue comes from the first one. The guild obtained from REST was not cached.

2019-12-03 16:53 UTC, Skillz4Killz commented
Why not have a property dedicated to the client? `this.client = client;`. You'd never have bugs like this again and users don't need to go `guild.shard.client`. One way or the other, `client` exists in the class.

Note: This needs typings updated to reflect the changes in the PR.

2019-12-06 03:40 UTC, abalabahaha requested changes

2019-12-06 03:40 UTC, abalabahaha commented on lib/structures/Guild.js
> +        this.shard = client.shards.get(client.guildShardMap[this.id]) || {
`||` is kind of unnecessary with `_client`

2019-12-06 03:40 UTC, abalabahaha commented on lib/structures/GuildChannel.js
> +            shard: {
Could use `guild._client` here and this wouldn't be necessary either.

2019-12-27 03:44 UTC, Apacheli commented
Sorry for delaying so long. I completely forgot about this. Happy late holidays lol

2019-12-31 23:51 UTC, abalabahaha approved these changes

2020-01-01 02:11 UTC, merged