Improved ESM support
abalabahaha/eris pull request #602
Opened 2019-12-27 07:13 UTC by LJNeon

ECMAScript modules can import CommonJS modules, however this is simply as a default export and can't take advantage of named exports. This PR adds named exports to Eris when imported by an ECMAScript module.
 - CommonJS support for Node.js 8+ (and for obsolete versions before 8).
 - Full ECMAScript support for Node.js 12+ (using an `eris/esm` import and/or flags).
 - Forwards compatibility with future versions of Node.js using [conditional exports](https://nodejs.org/docs/latest-v13.x/api/esm.html#esm_conditional_exports).
 - `Eris.VERSION` is temporarily removed from the ECMAScript exports, as importing JSON files is [experimental and behind a flag](https://nodejs.org/docs/latest-v13.x/api/esm.html#esm_experimental_json_modules). The code needed to add it back is commented out.
 - Updated dependencies, as every single one of them were outdated.

One side effect of this PR is that it prevents using [subpath imports](https://nodejs.org/docs/latest-v13.x/api/esm.html#esm_package_exports). Whether this is a good thing or not is worth discussion, but it causes no problems with normal use nor with TypeScript. An alternative method could be using the `eris/esm.mjs` subpath import, as while it's less appealing and lacks forwards compatibility it doesn't prevent use of subpaths.

2019-12-27 15:01 UTC, apacheli requested changes

2019-12-27 15:01 UTC, apacheli commented on esm.mjs
> +export {default as Base} from "./lib/structures/Base.js";
Little nitpick, but you can save a few characters by doing `import name from 'module'` and `export { name1, name2, ...names }`

2019-12-27 16:31 UTC, LJNeon commented on esm.mjs
> +export {default as Base} from "./lib/structures/Base.js";
Personally I think that it's far nicer to only import modules as needed, and to just export the rest as I did currently, if people disagree then I could change that easily though.

2019-12-27 20:44 UTC, Geo1088 commented on esm.mjs
> +export {default as Base} from "./lib/structures/Base.js";
I agree with eljay, I prefer using the more explicit `export from` whenever doing pass-through exports from other files. With `import`/`export`, it's not immediately obvious that the imported modules aren't being used directly within the file. I find this form a bit more readable.

2020-01-01 00:35 UTC, abalabahaha commented
This needs to be split into a couple different PRs/commits, and we decided that re-exporting `index.js` would be a better approach for now.

2020-01-01 00:35 UTC, closed without merging