break out message content type
abalabahaha/eris pull request #639
Opened 2020-02-01 15:14 UTC by alex-taxiera

This will allow TS users to easily extend the object we can pass to createMessage

2020-02-01 15:51 UTC, Skillz4Killz approved these changes

2020-02-01 15:51 UTC, Skillz4Killz requested changes

2020-02-01 15:51 UTC, Skillz4Killz commented on index.d.ts
> +    flags?: number
```suggestion
    flags?: number;
```

2020-02-01 17:25 UTC, Skillz4Killz approved these changes

2020-02-08 17:14 UTC, abalabahaha approved these changes

2020-02-08 17:15 UTC, merged