Allow Role input for createRole
abalabahaha/eris pull request #663
Opened 2020-03-17 17:37 UTC by LJNeon

There's only one inconsistency preventing Role objects from being passed to `Client#createRole()`, and being able to pass a Role object is relatively useful when cloning or recreating Roles. For example, without this change in order to recreate a Role you would need:
```js
await oldRole.delete();
const newRole = await guild.createRole({
  name: oldRole.name,
  permissions: oldRole.permissions.allow,
  color: oldRole.color,
  hoist: oldRole.hoist,
  mentionable: oldRole.mentionable,
});
await newRole.editPosition(oldRole.position);
```
However this PR would reduce that code to:
```js
await oldRole.delete();
const newRole = await guild.createRole(oldRole);
await newRole.editPosition(oldRole.position);
```

2020-03-18 02:45 UTC, Apacheli commented
Perhaps we could change `Role#permission` into a number. This would be a breaking change, but I don't believe it would affect the use case of most end users.

2020-03-18 05:37 UTC, LJNeon commented
I would think getting role permissions is a relatively common use case. It also removes all the convenience that the `Permission` class provides which seems like a bad idea.

2020-03-18 11:14 UTC, Skillz4Killz commented
> I would think getting role permissions is a relatively common use case. It also removes all the convenience that the `Permission` class provides which seems like a bad idea.

How so?

2020-03-18 13:59 UTC, LJNeon commented
All it'd be doing is removing ease of use for practically no benefit, this doesn't seem worth it at all just because it's not one of the most common use cases.

2020-03-19 05:39 UTC, abalabahaha requested changes

2020-03-19 05:39 UTC, abalabahaha commented on lib/Client.js
> +            permissions: options instanceof Role ? options.permissions.allow : options.permissions,
Might as well just run `instanceof Permission` here

2020-03-19 07:06 UTC, LJNeon commented on lib/Client.js
> +            permissions: options instanceof Role ? options.permissions.allow : options.permissions,
Done.

2020-03-21 12:07 UTC, Khaaz submitted a review, later dismissed

2020-04-01 11:00 UTC, abalabahaha approved these changes

2020-04-01 11:00 UTC, merged