Add support for crossposting messages
abalabahaha/eris pull request #901
Opened 2020-04-15 10:15 UTC by bsian03

This is not yet documented, however please see [here](https://github.com/discord/discord-api-docs/issues/1510) for more details,
> The endpoint is now accessible to bots, but there’s a few things... which I need to fix up before I’d be comfortable documenting it.

2020-04-15 10:26 UTC, Khaazz commented on lib/structures/NewsChannel.js
> +    crosspost(messageID) {
This should probably crosspostMessage as well?

2020-04-15 10:26 UTC, Khaazz commented on index.d.ts
> +    crosspost(channelID: string, messageID: string): Promise<Message>;
This should be crosspostMessage as mentionned by cat

2020-04-15 10:32 UTC, Khaaz submitted a review, later dismissed

2020-04-15 10:32 UTC, Khaazz commented on lib/structures/NewsChannel.js
> +        return this.client.crosspost.call(this.client, this.id, messageID);
Also since you changed client to be crosspostMessage, the client call should be on `crosspostMessage`. Same goes for the others

2020-04-16 01:22 UTC, abalabahaha requested changes
Would prefer docs to say crosspost too, maybe "Crosspost (publish) a message"

2020-04-16 02:18 UTC, abalabahaha approved these changes

2020-04-16 02:18 UTC, merged