Add support for GuildPreview endpoint
abalabahaha/eris pull request #906
Opened 2020-04-15 15:03 UTC by Khaazz

This PR brings support for GuildPreview as documented in discord/discord-api-docs#1405
This endpoint can only be used on public guilds
- GuildPreview endpoint `guilds/:guildID/preview`
- `getGuildPreview` method
- updated typings

2020-04-15 15:14 UTC, Skillz4Killz commented on index.d.ts
> +    icon: string;
```suggestion
    icon: string | null;
```

2020-04-15 15:14 UTC, Skillz4Killz commented on index.d.ts
> +    splash: string;
```suggestion
    splash: string | null;
```

2020-04-15 15:14 UTC, Skillz4Killz commented on index.d.ts
> +    discovery_splash: string;
```suggestion
    discovery_splash: string | null;
```

2020-04-15 15:14 UTC, Skillz4Killz commented on index.d.ts
> +    description: string;
```suggestion
    description: string | null;
```

2020-04-15 15:18 UTC, Khaazz commented
Yep my bad, forgot to authorize null on those, thank you 👍

2020-04-16 01:44 UTC, abalabahaha requested changes
Needs a wrapper struct

2020-04-27 06:59 UTC, abalabahaha approved these changes

2020-04-27 06:59 UTC, merged