Support for withCount field for GUILD endpoint
abalabahaha/eris pull request #920
Opened 2020-04-24 19:20 UTC by Khaazz

Ref discord/discord-api-docs#1528

- `withCount` for `getRESTGuild` method
- `approximateMemberCount` property on Guild
- `approximatePresenceCount` property on Guild

2020-04-27 06:44 UTC, abalabahaha requested changes

2020-04-27 06:44 UTC, abalabahaha commented on index.d.ts
> +    getRESTGuild(guildID: string, withCount?: boolean): Promise<Guild>;
Should be `withCounts`

2020-04-27 06:44 UTC, abalabahaha commented on lib/Client.js
> +        return this.requestHandler.request("GET", Endpoints.GUILD(guildID), true, withCount).then((guild) => new Guild(guild, this));
I'm not seeing how passing a boolean as the request body passed any of your local tests. Should be passing `with_counts` as the parameter.

2020-05-04 21:27 UTC, Khaazz commented
I think my brain broke. Should work now thanks

2020-05-06 14:24 UTC, abalabahaha approved these changes

2020-05-06 14:26 UTC, merged